#!/bin/bash
set -e

# This is the host-executable that is executed to start the compiler

echo "Starting LaTeX Compiler..."



SCRIPT_PATH="$(readlink -f "$0")"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"


export DOCKER_CLI_HINTS=false

podman build --pull=false -t latex-compiler "$SCRIPT_DIR/src"

podman run --rm -it \
    --network none \
    --cap-drop ALL \
    --tmpfs /latex_compiler/.tmpfs:rw,size=4096m \
    -v $1:/host_mount \
    latex-compiler

