#!/bin/bash
set -e


echo "Building..."


# Work from source directory
mkdir -p ./.tmpfs/src
cd ./.tmpfs/src/


# Make newest source available
cp -rf /host_mount/. ./



# Compile the PDF
latexmk -pdf main.tex


# Put back the compiled PDF
cp -f main.pdf /host_mount/


echo "Done!"
